import type { MapShop } from "../_types/map.types";

export const MAP_SHOPS: MapShop[] = [
  {
    id: "gachagacha",
    name: "가챠가챠",
    address: "서울시 마포구 와우산로 22-1",
    region: "홍대입구역 도보 12분",
    tags: ["가챠샵", "키치", "캐릭터"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5569,
    longitude: 126.9228,
    isLiked: true,
  },
  {
    id: "momone",
    name: "모모네 소품샵",
    address: "서울시 성동구 서울숲로 12-2, 1층",
    region: "서울숲역 도보 5분",
    tags: ["가챠샵", "키치", "캐릭터"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5448,
    longitude: 127.0445,
    isLiked: false,
  },
  {
    id: "lucky-clover",
    name: "클로버",
    address: "서울시 마포구 연남로 8",
    region: "홍대입구역 도보 8분",
    tags: ["문구", "미니멀"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5618,
    longitude: 126.9257,
    isLiked: false,
  },
  {
    id: "daily-object",
    name: "데일리 오브젝트",
    address: "서울시 성동구 연무장길 18",
    region: "성수역 도보 6분",
    tags: ["인테리어소품", "잡화", "선물"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5439,
    longitude: 127.0547,
    isLiked: false,
  },
  {
    id: "tiny-market",
    name: "타이니 마켓",
    address: "서울시 성동구 서울숲4길 11",
    region: "서울숲역 도보 7분",
    tags: ["잡화", "문구", "팬시"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5464,
    longitude: 127.0437,
    isLiked: true,
  },
  {
    id: "paper-garden",
    name: "페이퍼 가든",
    address: "서울시 마포구 동교로 221",
    region: "홍대입구역 도보 9분",
    tags: ["문구", "팬시", "선물"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5607,
    longitude: 126.9238,
    isLiked: false,
  },
  {
    id: "little-room",
    name: "리틀룸",
    address: "서울시 마포구 성미산로 152",
    region: "홍대입구역 도보 13분",
    tags: ["인테리어소품", "잡화"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5654,
    longitude: 126.9236,
    isLiked: false,
  },
  {
    id: "pink-drawer",
    name: "핑크 드로어",
    address: "서울시 마포구 연희로1길 25",
    region: "홍대입구역 도보 10분",
    tags: ["팬시", "캐릭터", "선물"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5616,
    longitude: 126.9282,
    isLiked: true,
  },
  {
    id: "object-house",
    name: "오브젝트 하우스",
    address: "서울시 성동구 성수이로 32",
    region: "성수역 도보 5분",
    tags: ["인테리어소품", "잡화", "미니멀"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5428,
    longitude: 127.0566,
    isLiked: false,
  },
  {
    id: "small-present",
    name: "작은 선물",
    address: "서울시 성동구 왕십리로 98",
    region: "서울숲역 도보 9분",
    tags: ["선물", "문구", "잡화"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5482,
    longitude: 127.0456,
    isLiked: false,
  },
  {
    id: "mood-store",
    name: "무드 스토어",
    address: "서울시 성동구 성수일로 41",
    region: "성수역 도보 4분",
    tags: ["인테리어소품", "미니멀"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5451,
    longitude: 127.0559,
    isLiked: false,
  },
  {
    id: "hello-bunny",
    name: "헬로 버니",
    address: "서울시 마포구 와우산로 128",
    region: "홍대입구역 도보 11분",
    tags: ["캐릭터", "팬시", "선물"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5548,
    longitude: 126.9271,
    isLiked: true,
  },
  {
    id: "green-table",
    name: "그린 테이블",
    address: "서울시 성동구 서울숲2길 17",
    region: "서울숲역 도보 6분",
    tags: ["인테리어소품", "잡화"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5461,
    longitude: 127.0419,
    isLiked: false,
  },
  {
    id: "mini-planet",
    name: "미니 플래닛",
    address: "서울시 마포구 동교로38길 13",
    region: "홍대입구역 도보 7분",
    tags: ["가챠샵", "캐릭터", "키치"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5623,
    longitude: 126.9251,
    isLiked: false,
  },
  {
    id: "paper-mood",
    name: "페이퍼 무드",
    address: "서울시 마포구 연남로3길 14",
    region: "홍대입구역 도보 9분",
    tags: ["문구", "미니멀", "선물"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5634,
    longitude: 126.9248,
    isLiked: true,
  },
  {
    id: "soft-object",
    name: "소프트 오브젝트",
    address: "서울시 성동구 연무장5길 19",
    region: "성수역 도보 5분",
    tags: ["인테리어소품", "잡화"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5436,
    longitude: 127.0538,
    isLiked: false,
  },
  {
    id: "yellow-basket",
    name: "옐로 바스켓",
    address: "서울시 마포구 성미산로29길 22",
    region: "홍대입구역 도보 14분",
    tags: ["잡화", "팬시", "선물"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5661,
    longitude: 126.9246,
    isLiked: false,
  },
  {
    id: "tiny-letter",
    name: "타이니 레터",
    address: "서울시 마포구 동교로46길 9",
    region: "홍대입구역 도보 12분",
    tags: ["문구", "팬시"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5642,
    longitude: 126.9263,
    isLiked: true,
  },
  {
    id: "cozy-shelf",
    name: "코지 셸프",
    address: "서울시 성동구 서울숲6길 21",
    region: "서울숲역 도보 8분",
    tags: ["인테리어소품", "미니멀"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5472,
    longitude: 127.0424,
    isLiked: false,
  },
  {
    id: "happy-day",
    name: "해피 데이",
    address: "서울시 마포구 양화로19길 27",
    region: "홍대입구역 도보 6분",
    tags: ["팬시", "캐릭터", "잡화"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5588,
    longitude: 126.9259,
    isLiked: false,
  },
  {
    id: "blue-corner",
    name: "블루 코너",
    address: "서울시 성동구 아차산로7길 15",
    region: "성수역 도보 4분",
    tags: ["잡화", "미니멀"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5453,
    longitude: 127.0573,
    isLiked: true,
  },
  {
    id: "mini-drawer",
    name: "미니 드로어",
    address: "서울시 마포구 동교로27길 11",
    region: "홍대입구역 도보 7분",
    tags: ["문구", "잡화", "팬시"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5599,
    longitude: 126.9247,
    isLiked: false,
  },
  {
    id: "orange-room",
    name: "오렌지 룸",
    address: "서울시 성동구 연무장길 42",
    region: "성수역 도보 7분",
    tags: ["인테리어소품", "키치"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5429,
    longitude: 127.0555,
    isLiked: false,
  },
  {
    id: "bear-market",
    name: "베어 마켓",
    address: "서울시 마포구 연희로1길 41",
    region: "홍대입구역 도보 11분",
    tags: ["캐릭터", "팬시", "선물"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5625,
    longitude: 126.9285,
    isLiked: true,
  },
  {
    id: "studio-mood",
    name: "스튜디오 무드",
    address: "서울시 성동구 서울숲길 33",
    region: "서울숲역 도보 6분",
    tags: ["인테리어소품", "잡화"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5457,
    longitude: 127.0431,
    isLiked: false,
  },
  {
    id: "cloud-paper",
    name: "클라우드 페이퍼",
    address: "서울시 마포구 동교로39길 18",
    region: "홍대입구역 도보 10분",
    tags: ["문구", "팬시", "미니멀"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5627,
    longitude: 126.9232,
    isLiked: false,
  },
  {
    id: "tiny-friends",
    name: "타이니 프렌즈",
    address: "서울시 마포구 와우산로29길 14",
    region: "홍대입구역 도보 8분",
    tags: ["캐릭터", "가챠샵", "키치"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5564,
    longitude: 126.9276,
    isLiked: true,
  },
  {
    id: "simple-home",
    name: "심플 홈",
    address: "서울시 성동구 성수이로7길 21",
    region: "성수역 도보 6분",
    tags: ["인테리어소품", "미니멀"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5434,
    longitude: 127.0581,
    isLiked: false,
  },
  {
    id: "gift-box",
    name: "기프트 박스",
    address: "서울시 마포구 성미산로 117",
    region: "홍대입구역 도보 15분",
    tags: ["선물", "잡화", "팬시"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5647,
    longitude: 126.9219,
    isLiked: false,
  },
  {
    id: "little-cloud",
    name: "리틀 클라우드",
    address: "서울시 성동구 서울숲9길 13",
    region: "서울숲역 도보 9분",
    tags: ["잡화", "문구", "선물"],
    imageUrl: "/images/icons/clover.webp",
    latitude: 37.5478,
    longitude: 127.0443,
    isLiked: true,
  },
];
